### ISSUE TITLE
log_folder=None not working any more in 0.1b.10

### ISSUE THREAD

**Issue by wulmer** [SmokinCaterpillar/pypet#16]
Hi,
I just upgraded from 0.1b.9 to the new release 0.1b.10 and most things smoothly upgraded. There was a minor issue with the logging config. In [0.1b.9](http://pypet.readthedocs.org/en/0.1b.9/pypetdoc/environmentdoc.html#pypet.environment.Environment) it was possible to specify `log_folder=None` in the `Environment` constructor, whereas this option has vanished in [0.1b.10](http://pypet.readthedocs.org/en/0.1b.10/pypetdoc/environmentdoc.html#pypet.environment.Environment).
Using `log_folder=None` in 0.1b.10 raises an error in `pypetlogging.py`:

    File "c:\home\hub\uq\venv\lib\site-packages\pypet\pypetlogging.py", line 125, in _change_logging_kwargs
        handler_dict['filename'] = os.path.join(log_folder, handler_dict['filename'])

because the `log_folder` is None.
Is there another way to disable logging in `0.1b.10` or could the old behavior be restored? 
In the latter case, I can try to submit a patch for this, but I want to clarify first which behavior is the right one.

Regards.
Wolfgang

**Comment by SmokinCaterpillar** [comment]
Hi, 

the new equivalent of 'log_folder=None'  should be 'log_config=None'. Does this work? 

Cheers, 
Robert 

On 17 April 2015 15:54:47 CEST, wulmer <notifications@github.com> wrote:
>Hi,
>I just upgraded from 0.1b.9 to the new release 0.1b.10 and most things
>smoothly upgraded. There was a minor issue with the logging config. In
>[0.1b.9](http://pypet.readthedocs.org/en/0.1b.9/pypetdoc/environmentdoc.html#pypet.environment.Environment)
>it was possible to specify `log_folder=None` in the `Environment`
>constructor, whereas this option has vanished in
>[0.1b.10](http://pypet.readthedocs.org/en/0.1b.10/pypetdoc/environmentdoc.html#pypet.environment.Environment).
>Using `log_folder=None` in 0.1b.10 raises an error in
>`pypetlogging.py`:
>
>File "c:\home\hub\uq\venv\lib\site-packages\pypet\pypetlogging.py",
>line 125, in _change_logging_kwargs
>handler_dict['filename'] = os.path.join(log_folder,
>handler_dict['filename'])
>
>because the `log_folder` is None.
>Is there another way to disable logging in `0.1b.10` or could the old
>behavior be restored? 
>In the latter case, I can try to submit a patch for this, but I want to
>clarify first which behavior is the right one.
>
>Regards.
>Wolfgang
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SmokinCaterpillar/pypet/issues/16

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wulmer** [comment]
Yes. `log_config=None` works. However the documentation says about `log_config`:

> Set to None if you don’t want pypet to configure logging.
> If not specified, the default settings are used.

I interpreted the `configure logging` equally to the `default settings`. IMHO having a different behavior for `log_config=None` and for `log_config` not being specified seems unintuitive.

What about disabling logging with `log_config=None` and using default logging config with `log_config=pypet.pypetlogging.DEFAULT` ?

**Comment by wulmer** [comment]
Update: `log_config=None` doesn't work. It does not crash but it does *not* disable logging. I think it simply uses the `windows_default.ini` logging config instead.

**Comment by SmokinCaterpillar** [comment]
Hmm, that's odd. I am currently away, but I can look into this tomorrow.

**Comment by SmokinCaterpillar** [comment]
Hmm, I can't replicate the error on Linux. For instance, setting explicitly `log_config=None` in the first example (https://pythonhosted.org/pypet/examplesdoc/example_01.html) disables all logging activity. That is no files are created and no log-messages are printed to the console. 

Does setting `log_conifg=None` work on your machine with the first example?

**Comment by wulmer** [comment]
Good guess. It was actually the `log_levels` and `logger_names` argument. Each one independently enables logging, even if `log_config=None`.

I can't find a description of those parameters in the [current documentation for `Environment`](https://pypet.readthedocs.org/en/0.1b.10/pypetdoc/environmentdoc.html). What would be the correct usage?

Based on the description of `log_config` I assumed that setting it to `None` would effectively disable *all* logging. Only if `log_config` was set to one of the default logging configs, the parameters `log_(folder|level|names)` would be used, but not if `log_config` was `None`.

**Comment by SmokinCaterpillar** [comment]
Yes I figured this. In the next version, you will only be able to specify either `log_config` or `logger_names` and `log_levels` and a `log_folder`. If `log_config` and at least one of the others is given, an error is explicitly raised. 

And you're right, I the docs could be better. The basic idea was to move away from this rather rigid scheme of just listing a `log_folder` and `logger_names` and `log_levels`, but allow for fully customizable [logging configurations](https://docs.python.org/2/library/logging.config.html). Such that you can use normal logging `.ini` files and things like filters, for instance. However, for simple logging configurations and backwards compatibility, I also kept the old keywords, which just tweak the default settings, i.e. change the log-folder and loggers and levels, but not more than that.
This behaviour is more or less hidden in the docs (second paragraph):

>log_config –
>
>Can be path to a logging .ini file specifying the logging configuration. For an example of such a file see Logging. Can also be a dictionary that is accepted by the built-in logging module. Set to None if you don’t want pypet to configure logging.
>
>If not specified, the default settings are used. Moreover, you can manually tweak the default settings without creating a new ini file. Instead of the log_config parameter, pass a log_folder, a list of logger_names and corresponding log_levels to fine grain the loggers to which the default settings apply.
>
>For example:
>
>log_folder='logs', logger_names='('pypet', 'MyCustomLogger'), log_levels=(logging.ERROR, logging.INFO)

Do you have any suggestion or idea how to make this better and more explicit?

**Comment by wulmer** [comment]
The only misunderstanding I had with the current documentation was that it did not specify how to disable logging using the *old* arguments. Especially the fact that we mixed old and new style arguments messed up the logging configuration.

Your planned fix for the next version where either `log_config` or the other arguments can be used (and not together) will make this clear (at least when executing the code).

BTW: Is it really necessary to have different logging INI files for Windows and Linux (i.e., `default.ini` and `windows_default.ini`)? The only difference I can see between them is the use of `\\` vs. `/`. In my experience, Python is quite capable of dealing with this difference so I expect the Windows version to accept logging config paths with `/` instead of `\\`. If you cannot try this on a Windows machine, I can test it for you.

**Comment by SmokinCaterpillar** [comment]
Probably it's not necessary. But the only testing environment for Windows that I currently have is AppVeyor, so using separate files for Windows and Linux is more or less overcautious^^. So yes, if you could test this for me, would be nice.

**Comment by SmokinCaterpillar** [comment]
Great thanks!

I just wonder why you are now listed within the contributor panel, but still the number of contributors is 2. Hmm maybe it updates later when the develop branch gets merged into master.
