### ISSUE TITLE
Distribute runs over multiple nodes

### ISSUE THREAD

**Issue by anandtrex** [SmokinCaterpillar/pypet#19]
pypet solves a lot of problems that we have with simulations (as advertised). But being able to distribute runs over multiple nodes for different parameter values would really be awesome for large parameter space exploration for long running simulations. Are there any plans to support this in the future?

**Comment by SmokinCaterpillar** [comment]
That is definitely a nice feature, and I thought about it already. However, this is something that is planned for the (very) long run. Unfortunately, I don't have the time to work on such an extension at the moment. But maybe you can split your long running simulation among different nodes with different environments and trajectories for each node and then later [merge them together](http://pypet.readthedocs.org/en/latest/cookbook/trajectory.html#merging-and-backup)?

**Comment by SmokinCaterpillar** [comment]
I am currently experimenting with SCOOP ('http://scoop.readthedocs.org/en/latest/usage.html') and SAGA-Python ('http://saga-python.readthedocs.org/en/latest/'). Both seem to integrate well, this feature might already be available in the next version.

**Comment by SmokinCaterpillar** [comment]
So this has been merged into master. If you wish you can try it out by installing from the master branch. 

The master branch documentation can be found here: https://pypet.readthedocs.org/en/master/
New SCOOP multiprocessing is explained here: https://pypet.readthedocs.org/en/master/cookbook/environment.html#multiprocessing-with-a-cluster-or-a-multi-server-framework

Here is an example on how to use SCOOP: https://pypet.readthedocs.org/en/master/examplesdoc/example_21.html
And SAGA-Python: https://pypet.readthedocs.org/en/master/examplesdoc/example_22.html

**Comment by anandtrex** [comment]
That's great. Thanks for the update. I tried the [provided scoop example](https://pypet.readthedocs.org/en/master/examplesdoc/example_21.html) with python 3.4 with an installation of pypet from the master branch. 

Both running on a single host on multiple cores and on multiple hosts seem to work according to the logs. But there are a couple of (minor) bugs:

When running on a single node, multiple core using `python3 -m scoop pypet_test.py`, I get this error:
```
Could not configure logging system because of: KeyError('formatters',)Traceback (most recent call last):
  File "/some/path/lib/python3.4/site-packages/pypet-0.1b.13dev-py3.4.egg/pypet/environment.py", line 218, in _configure_logging
    logging_manager.make_logging_handlers_and_tools(multiproc=True)
  File "/some/path/lib/python3.4/site-packages/pypet-0.1b.13dev-py3.4.egg/pypet/pypetlogging.py", line 628, in make_logging_handlers_and_tools
    fileConfig(memory_file, disable_existing_loggers=False)
  File "/usr/lib/python3.4/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python3.4/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib/python3.4/configparser.py", line 937, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```

When running on multiple nodes i.e. running using `python3 -m scoop --hostfile hosts.txt script.py`, I don't see the above error either in stdout or in the log files, and the log files says the simulation has finished running. But the simulation doesn't exit. It just hangs as if it's still running.

**Comment by SmokinCaterpillar** [comment]
Hi, 

thanks for looking into the multi server examples. I am currently on holiday in Panama and I don't have access to my laptop. I am back on the 20th and then I am going to look into the bugs. 

Thanks and cheers, 
Robert 

On October 5, 2015 10:04:57 AM GMT-05:00, Anand <notifications@github.com> wrote:
>That's great. Thanks for the update. I tried the [provided scoop
>example](https://pypet.readthedocs.org/en/master/examplesdoc/example_21.html)
>with python 3.4 with an installation of pypet from the master branch. 
>
>Both running on a single host on multiple cores and on multiple hosts
>seem to work according to the logs. But there are a couple of (minor)
>bugs:
>
>When running on a single node, multiple core using `python3 -m scoop
>pypet_test.py`, I get this error:
>```
>Could not configure logging system because of:
>KeyError('formatters',)Traceback (most recent call last):
>File
>"/some/path/lib/python3.4/site-packages/pypet-0.1b.13dev-py3.4.egg/pypet/environment.py",
>line 218, in _configure_logging
>    logging_manager.make_logging_handlers_and_tools(multiproc=True)
>File
>"/some/path/lib/python3.4/site-packages/pypet-0.1b.13dev-py3.4.egg/pypet/pypetlogging.py",
>line 628, in make_logging_handlers_and_tools
>    fileConfig(memory_file, disable_existing_loggers=False)
>  File "/usr/lib/python3.4/logging/config.py", line 76, in fileConfig
>    formatters = _create_formatters(cp)
>File "/usr/lib/python3.4/logging/config.py", line 109, in
>_create_formatters
>    flist = cp["formatters"]["keys"]
>  File "/usr/lib/python3.4/configparser.py", line 937, in __getitem__
>    raise KeyError(key)
>KeyError: 'formatters'
>```
>
>When running on multiple nodes i.e. running using `python3 -m scoop
>--hostfile hosts.txt script.py`, I don't see the above error either in
>stdout or in the log files, and the log files says the simulation has
>finished running. But the simulation doesn't exit. It just hangs as if
>it's still running.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SmokinCaterpillar/pypet/issues/19#issuecomment-145561738

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SmokinCaterpillar** [comment]
Does the Error message persist if you set "freeze_input=False"?

**Comment by anandtrex** [comment]
Yup. Using freeze_input=False seems to prevent this issue from happening.

**Comment by SmokinCaterpillar** [comment]
I merged a fix into master. The frozen input was not stored anywhere. So pypet was reconfiguring all runs - including the logging - again and again for every scoop worker which caused the errors.

**Comment by SmokinCaterpillar** [comment]
The version supporting SCOOP will be released some time this week on PyPi.

**Comment by SmokinCaterpillar** [comment]
new 0.2b1 version now supports SCOOP
