### ISSUE TITLE
ENH: Set niceness of run

### ISSUE THREAD

**Issue by toddrjen** [SmokinCaterpillar/pypet#22]
You can set the cpu and memory caps for multiprocessing runs.  However, these are fixed.  It would be useful if we could instead (or in addition) set the niceness of the run, which more dynamically scales to the available resources.  Python has built-in support for setting niceness, so this should be possible without any additional dependencies.

**Comment by SmokinCaterpillar** [comment]
Hi, what do you mean by "these are fixed"? But I agree setting niceness would be a neat feature. In the meantime you can do this manually at the beginning of each run via:

    import os
    target_niceness = 10 # or whatever value you want
    current_niceness = os.nice(0)
    os.nice(target_niceness - current_niceness)

I guess the pypet implementation will look quite similar to this.

Do you have any idea how this may work under windows? Or what is the Windows equivalent of nice?

**Comment by SmokinCaterpillar** [comment]
Has already been included in develop, will be merged to master soon.

**Comment by toddrme2178** [comment]
Oh, wow, that was fast.  Thanks a lot!

**Comment by SmokinCaterpillar** [comment]
Merged to master :-)
