### ISSUE TITLE
ENH: Store original trajectory name (without timestamp)

### ISSUE THREAD

**Issue by toddrjen** [SmokinCaterpillar/pypet#23]
When you set `add_time=True`, the time is appended to the end of the trajectory name.  This is useful for uniquely identifying the trajectory, but I think it would also be useful to store the original name without the timestamp (perhaps `v_original_name`).  

This can be useful, for example, in plot titles.  You can use the full name (with timestamp) for the plot file name, but you probably don't need to see that in the plot.  

For consistency, this would probably still be defined when `add_time=False`, but would be identical to the normal name.

**Comment by SmokinCaterpillar** [comment]
Hmm, do you really think that is necessary? There are already a lot of `v_` properties. Moreover, you can still retrieve the original name like this:

    from pypet import Trajectory

    t = Trajectory('my_traj', add_time=True)

    print(t.v_name)   # Name with time
    print(t.v_name.rsplit('_', 4)[0])  # Name without time

**Comment by SmokinCaterpillar** [comment]
inactive
