### ISSUE TITLE
Check if parameter is set before starting run

### ISSUE THREAD

**Issue by michaelaye** [SmokinCaterpillar/pypet#28]
First, thanks for this great project. Hope I can contribute to this in the future with a PR or two!

I just started playing with it, and was it by something that I believe is avoidable (maybe not?).

I used a parameter inside my run function that I forgot to add. This resulted in all my parameter spaces being explored, resulting in many many error files just stating that a single run failed, due to the missing trajectory parameter.
(Of course I should have made a test run without that, but I was so eager to let it run! ;)

Is that maybe checkable before the big run starts?

**Comment by SmokinCaterpillar** [comment]
Thanks. Good to hear that you like it. Of course, contributions are always welcome.

Testing beforehand if a parameter exists seems difficult to me. Sounds like some sort of pre-compiling of your run function. However, there is a simple way to test your simulation with just a single run before starting your massive explorations, just uncomment your parameter exploration. In this case, *pypet* starts just one run with the default parameters.

So if this is your code:

    traj.f_explore(my_expl_dictionary)
    env.run(my_simulation)

do this instead:

    # traj.f_explore(my_expl_dictionary)
    env.run(my_simulation)

**Comment by michaelaye** [comment]
Thanks for your fast reply! I agree, that's the most efficient way and that's what I should have done anyway.
