### ISSUE TITLE
Dismissing Python 2 Support

### ISSUE THREAD

**Issue by SmokinCaterpillar** [SmokinCaterpillar/pypet#38]
Supporting Python 2 and 3 is a hard endeavour and blows up the code base.
Moreover, maintaining the code base to support Python 2 and 3 is very time consuming.
I think about dropping Python 2 support in future releases entirely.

This will simplify CI testing a lot and lead to a much more manageable and readable code base.
Besides, Python 3 is the present and, of course, the future of Python.

**Comment by SmokinCaterpillar** [comment]
PS: https://asmeurer.github.io/blog/posts/moving-away-from-python-2/

**Comment by toddrjen** [comment]
I have no objection.  I have switched entirely to python 3 myself for similar reasons.

**Comment by gvoysey** [comment]
Same here.

**Comment by SmokinCaterpillar** [comment]
I'm currently finalizing the new Python3 only version, will be released soon.

**Comment by SmokinCaterpillar** [comment]
And it's gone...
