### ISSUE TITLE
The behaviour of f_to_dict is counterintuitive

### ISSUE THREAD

**Issue by maharjun** [SmokinCaterpillar/pypet#41]
The behaviour of `NNGroupNode::f_to_dict` is not intuitive at all. most importantly, I cannot seem to use it to get a nested dict representation of the subtree under a particular group node. This is because, the nested flag gives a dictionary that is nested from the very first level and not from the group node that is calling it. I propose the following change to the function f_to_dict.

1.  Make the short_names and nested options mutually exclusive
2.  Make the nested option return a dict with the first level keys being the children of the current group node.

Although the above wil break the API, I personally find it impractical to use f_to_dict as of now anywhere.

**Comment by SmokinCaterpillar** [comment]
Hi, yes that sounds like a better behaviour than now. I'll look into it!

**Comment by SmokinCaterpillar** [comment]
Well, so changing the default behaviour of `f_to_dict` would actually break quite some parts.
However, what I can do, and what IMO makes sense is changing the behaviour for `nested=True`.
In this case the resulting dictionary will start with the current node's children as the first entries. 
Does that solve your problem?

**Comment by maharjun** [comment]
Sure! That does sound good!

On May 8, 2017 20:20, "Robert Meyer" <notifications@github.com> wrote:

Well, so changing the default behaviour of f_to_dict would actually break
quite some parts.
However, what I can do, and what IMO makes sense is changing the behaviour
for nested=True.
In this case the resulting dictionary will start with the current node's
children as the first entries.
Does that solve your problem?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SmokinCaterpillar/pypet/issues/41#issuecomment-299948579>,
or mute the thread
