### ISSUE TITLE
Trajectory pickling results all the time irrespective of v_full_copy

### ISSUE THREAD

**Issue by maharjun** [SmokinCaterpillar/pypet#44]
From a preliminary observation, it appears that v_full_copy only applies to the whether the parameters are pickled or not. Howver, looking at the `__getstate__` implementations of the `HasSlots` class and the `Trajectory` class, it appears that there is no code that prevents result groups and the like from getting pickled. Have I missed something or is this by design. This would also explain the gradually increasing evaluation time as the population generations increase in my simulations (as a result of having to send a larger traj object each time across the network) (even after the fix in #43)

If the above is indeed the case, I think this is a crucial Issue as I'm dealing with simulation results that several GB's worth and having to transmit this data each generation makes adaptive exploration infeasible.

**Comment by SmokinCaterpillar** [comment]
Yes, I think you are right, but it's difficult to determine whether a node should be removed or not for pickling, so it may be easier to do that manually.

Have you tried to `traj.f_remove('results')` after evaluation of the results and starting a new round of adaptive exploration?

**Comment by SmokinCaterpillar** [comment]
inactive
