### ISSUE TITLE
Remove Deep Search Feature

### ISSUE THREAD

**Issue by maharjun** [SmokinCaterpillar/pypet#45]
The Deep Search Feature (i.e. searching for a node with a partial name) seems to be adding too much complexity to the code involved. Also, performing breadth first search becomes insanely slow in certain cases (e.g. issue #42 ). The reasons I can think of are:

1.  Inefficient in terms of speed
2.  Requires quite some complicated code to ensure unneeded things do not happen like accessing a wrong key or the like. (Also, by python zen, explicit is better than implicit ;))
3.  [2.] still has the potential of letting certain errors pass through.

I think it would be better without this. In any case, the system of wildcards is convenient enough for specifying complicated parts of the name like the set and run numbers.

**Comment by SmokinCaterpillar** [comment]
Hmm, I do like the deep search feature^^. However, in issue 42 this is taken to its limits. But I guess the fix I came up with may solve your problem.
