### ISSUE TITLE
Trajectory.f_copy does not copy the exploration range

### ISSUE THREAD

**Issue by maharjun** [SmokinCaterpillar/pypet#46]
From what I have observed, the default invocation of Trajectory.f_copy does not copy the exploration range of the parameters over to the new trajectory. This is again counterintuitive as a default call to a copy function should produce an identical object (irrespective of deepness of copy)

**Comment by SmokinCaterpillar** [comment]
Hmm that's odd, do you have an example.?

Looking into the code I see
`new_traj._run_information = self._run_information`,
so the range should be copied as well (i.e. that's just a reference and not a deep copy, but still).

**Comment by SmokinCaterpillar** [comment]
inactive
