### ISSUE TITLE
Brian2MonitorResult : does not implement the methods of brian2.monitors classes

### ISSUE THREAD

**Issue by BlackSquare73** [SmokinCaterpillar/pypet#47]
When we utilise the result from a Trajectory in the form of a Brian2MonitorResult class, this has the functionality of a pypet node, but does not have the methods that each particular monitor result would have.

Examples:
1. SpikeMonitor class lacks the .num_spikes() method;
2. PopulationRateMonitor class lacks the .smooth_rate() method.

It would allow for seamless integration if the Brian2MonitorResult class automatically detected the type of the monitor result it was recording and constructed the Brian2MonitorResult in a way that had both the pypet node functionality, as well as all the methods of the monitor class it was recording.

I suggest that a solution to this problem would lie in,

1) multiple inheritance of the Brian2MonitorResult class and the monitor class; or
2) a means of hacking the brian2 monitors so that a dummy form of the relevant brian2 monitor is created, and then loaded with the data from the Brian2MonitorResult class, and then fused together.

NOTE: I am using Python 2.7.x, as brian2 does, so it is necessary that the changes are also compatible with Python 2.7.x, as well as later versions.

**Comment by SmokinCaterpillar** [comment]
I'll look into adding the brian2 methods. However, I probably have to disappoint you here, but pypet does not support Python 2 any longer and the Python 2 codebase is legacy and won't be maintained any more.

**Comment by gvoysey** [comment]
brian2 is py3 compatible: https://pypi.python.org/pypi/Brian2 (thank
goodness).
