### ISSUE TITLE
Multiple single core test failures on python3.8: FAILED (failures=1, errors=69, skipped=101)

### ISSUE THREAD

**Issue by sanjayankur31** [SmokinCaterpillar/pypet#57]
These are the only ones I've run here:

- clone the repo
- set up a new virtual environment, `pew new pypet`
- `python setup.py install`
- `python pypet/tests/all_single_core_tests.py`

The output is attached. There are multiple failures:
[test-log.txt](https://github.com/SmokinCaterpillar/pypet/files/4669551/test-log.txt)

**Comment by SmokinCaterpillar** [comment]
Thanks, yes pypet needs some updates regarding newer pandas and python versions. @caglorithm do you want to look at it? I'm currently short on time (Maybe I can look at it next week for a bit).

**Comment by SmokinCaterpillar** [comment]
ok, I'm currently fixing it, there were only some minor issues with pandas
* HDFStore no longer supportin filters
* as_matrix has been removed and one simply needs to use values.

New version should be available soon.

**Comment by SmokinCaterpillar** [comment]
@sanjayankur31 can you install pypet 0.5.0 and rerun the tests?

**Comment by sanjayankur31** [comment]
Looks pretty good! Only 5 tests were skipped, the rest look fine. Complete log attached. 
[pypet-fedora-py3.8.3-tests.txt](https://github.com/SmokinCaterpillar/pypet/files/4715825/pypet-fedora-py3.8.3-tests.txt)

These are the dependency versions I'd run them with:

```
$ rpm -qa \*scipy\* \*brian2\* \*numpy\* \*hdf5\* \*pandas\* \*tables\*


python3-scipy-1.4.1-1.fc32.x86_64
python3-numpy-f2py-1.18.4-2.fc32.x86_64
python3-pandas-0.25.3-2.fc32.x86_64
hdf5-1.10.5-6.fc32.x86_64
python3-pandas-datareader-0.8.0-2.fc32.noarch
python3-brian2-2.3.0.2-1.fc32.x86_64
python3-numpy-1.18.4-2.fc32.x86_64
python3-tables-3.5.2-7.fc32.x86_64

$ python --version
Python 3.8.3
```

Fedora 33 now has Python 3.9, so I'll be able to report back once I've kicked off a build for that in a bit.

**Comment by sanjayankur31** [comment]
Also look good with Python3.9 on F33. Logs attached:

[pypet-python3.9-buildlog.txt](https://github.com/SmokinCaterpillar/pypet/files/4715928/pypet-python3.9-buildlog.txt)
[pypet-python3.9-rootlog.txt](https://github.com/SmokinCaterpillar/pypet/files/4715929/pypet-python3.9-rootlog.txt)

Package versions here:

```
python3-numpy-f2py-1:1.18.4-3.fc33.x86_64
python3-numpy-1:1.18.4-3.fc33.x86_64
python3-scipy-1.4.1-2.fc33.x86_64
python3-pandas-1.0.1-2.fc33.x86_64
python3-tables-3.5.2-8.fc33.x86_64
python3-brian2-2.3.0.2-2.fc33.x86_64
```

I've updated the Fedora packages to 0.5.0 now. That'll also run the builds on various other architectures. If something untoward happens, I'll report back. 

Thanks very much for looking into this so quickly.

**Comment by SmokinCaterpillar** [comment]
I'll do another 0.5.1 release today, this won't change anything in comparison to 0.5.0 except for some corrections in the docs and the readme

**Comment by SmokinCaterpillar** [comment]
0.5.1 is out
